
name: Greeting on variable day

on:
  workflow_dispatch

env:
  DAY_OF_WEEK: Monday

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
    steps:
    
      - uses: actions/checkout@v2
      # Install Node 12
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12

      # Install dependencies
      - name: Install package front
        run: npm install

      - name: "Say Hello Mona it's Monday"
        run: echo "$Greeting ${{ vars.FIRST_NAME }}. Today is $DAY_OF_WEEK!"

      - name: create env file
        run: |
         touch .env.development 
         echo BASE_URL=${{ vars.FIRST_NAME }} >> .env
        
      - name: npm run start
        run: npm run start
         
         
         
